language: objective-c
os: osx
osx_image: xcode7
env:
    # List by `instruments -s devices`
    - DESTINATION='platform=iOS Simulator,name=iPhone 5,OS=9.0'
    - DESTINATION='platform=iOS Simulator,name=iPhone 6,OS=9.0'
    - DESTINATION='platform=iOS Simulator,name=iPhone 6 Plus,OS=9.0'
    - DESTINATION='platform=iOS Simulator,name=iPhone 6s,OS=9.0'
    - DESTINATION='platform=iOS Simulator,name=iPhone 6s Plus,OS=9.0'
install:
    - make bootstrap
before_script:
    - script/cert --import
    - make deps
script:
    - make test
after_script:
    - script/cert --remove
